spring:
  application:
    name: apiQuoteFlow
  main:
    web-application-type: servlet
  web:
    resources:
      add-mappings: false
  datasource:
    name: quoteflow
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/quoteflow
    username: postgres
    password: root
server:
  port: 8080
